

POST http://localhost:5000/api/uploadfile HTTP/1.1
content-type: application/json

{
    "rID":120,
    "docFieldID": 6,
    "newFileLocation": 13,
    "filename": "FRS_Real Time Feasibility_V4_00.pdf",
    "versionNumber":2
}

###
GET http://localhost:5000/ HTTP/1.1